import { ExerciseState, Marketplace } from 'fuesim-digital-shared';
import {
    collectionDependencyMappingTable,
    elementTemplateToSetMappingTable,
    exerciseElementSetTable,
    exerciseElementTemplateTable,
    latestExerciseElementTemplateView,
} from '../schema.js';
import { BaseRepository } from './base-repository.js';
import { eq, desc, getTableColumns, sql, and, max } from 'drizzle-orm';

export class CollectionRepository extends BaseRepository {
    private latestCollectionNumbers(opts: { allowDraftState?: boolean }) {
        return this.databaseConnection.$with('latestSetVersionNumbersView').as(
            this.databaseConnection
                .select({
                    entityId: exerciseElementSetTable.entityId,
                    latestversion: max(exerciseElementSetTable.version).as(
                        'latestversion'
                    ),
                })
                .from(exerciseElementSetTable)
                .where(
                    opts.allowDraftState !== true
                        ? eq(exerciseElementSetTable.draftState, false)
                        : sql`true`
                )
                .groupBy(exerciseElementSetTable.entityId)
        );
    }

    private latestCollections(opts: { allowDraftState?: boolean }) {
        console.log(opts);
        const latestCollectionVersionNumbers = this.latestCollectionNumbers({
            allowDraftState: opts.allowDraftState,
        });

        return this.databaseConnection.$with('latestCollectionsView').as(
            this.databaseConnection
                .with(latestCollectionVersionNumbers)
                .select(getTableColumns(exerciseElementSetTable))
                .from(exerciseElementSetTable)
                .innerJoin(
                    latestCollectionVersionNumbers,
                    and(
                        eq(
                            exerciseElementSetTable.entityId,
                            latestCollectionVersionNumbers.entityId
                        ),
                        eq(
                            exerciseElementSetTable.version,
                            latestCollectionVersionNumbers.latestversion
                        )
                    )
                )
        );
    }

    public async getOrCreateDraftState(
        collectionEntityId: Marketplace.Set.EntityId
    ) {
        const result = this.onlySingle(
            await this.databaseConnection
                .select()
                .from(exerciseElementSetTable)
                .where(
                    and(
                        eq(
                            exerciseElementSetTable.entityId,
                            collectionEntityId
                        ),
                        eq(exerciseElementSetTable.draftState, true)
                    )
                )
        );

        if (result == null) {
            const latestVersion = this.strict(
                await this.getLatestCollectionByEntityId(collectionEntityId)
            );

            const newCollection = this.onlySingleStrict(
                await this.databaseConnection
                    .insert(exerciseElementSetTable)
                    .values({
                        ...latestVersion,
                        versionId: undefined, // versionId will be generated by the database
                        version: latestVersion.version + 1,
                        draftState: true,
                        visibility: 'private',
                    })
                    .returning()
            );

            await this.copyReferencesBetweenCollections(
                latestVersion.versionId,
                newCollection.versionId
            );

            await this.copyDependenciesBetweenCollections(
                latestVersion.versionId,
                newCollection.versionId
            );

            return newCollection;
        }

        return this.strict(result);
    }

    public async getCollectionVersionDependencies(
        collectionVersionId: Marketplace.Set.VersionId
    ) {
        return await this.databaseConnection
            .select(getTableColumns(collectionDependencyMappingTable))
            .from(exerciseElementSetTable)
            .innerJoin(
                collectionDependencyMappingTable,
                eq(
                    exerciseElementSetTable.versionId,
                    collectionDependencyMappingTable.dependentCollectionVersionId
                )
            )
            .where(
                and(
                    eq(exerciseElementSetTable.versionId, collectionVersionId),
                    eq(
                        collectionDependencyMappingTable.dependentCollectionVersionId,
                        collectionVersionId
                    )
                )
            );
    }

    public async removeCollectionVersionDependency(
        dependentCollectionVersionId: Marketplace.Set.VersionId,
        dependencyCollectionVersionId: Marketplace.Set.VersionId
    ) {
        return await this.databaseConnection
            .delete(collectionDependencyMappingTable)
            .where(
                and(
                    eq(
                        collectionDependencyMappingTable.dependentCollectionVersionId,
                        dependentCollectionVersionId
                    ),
                    eq(
                        collectionDependencyMappingTable.collectionVersionId,
                        dependencyCollectionVersionId
                    )
                )
            );
    }

    public async addCollectionVersionDependency(
        dependentCollectionVersionId: Marketplace.Set.VersionId,
        dependencyCollectionVersionId: Marketplace.Set.VersionId
    ) {
        const dependent = this.strict(
            await this.getCollectionByVersionId(dependentCollectionVersionId)
        );
        const dependency = this.strict(
            await this.getCollectionByVersionId(dependencyCollectionVersionId)
        );

        return await this.databaseConnection
            .insert(collectionDependencyMappingTable)
            .values({
                collectionVersionId: dependency.versionId,
                collectionEntityId: dependency.entityId,
                dependentCollectionVersionId: dependent.versionId,
                dependentCollectionEntityId: dependent.entityId,
            })
            .returning();
    }

    public async saveDraftState(collectionEntityId: Marketplace.Set.EntityId) {
        const result = await this.databaseConnection
            .update(exerciseElementSetTable)
            .set({ draftState: false })
            .where(
                and(
                    eq(exerciseElementSetTable.entityId, collectionEntityId),
                    eq(exerciseElementSetTable.draftState, true)
                )
            )
            .returning();

        return this.onlySingleStrict(result);
    }

    public async createFirstCollectionVersion(title: string, owner: string) {
        console.log(
            'Creating exercise set with title:',
            title,
            'for owner:',
            owner
        );
        const result = await this.databaseConnection
            .insert(exerciseElementSetTable)
            .values({
                title,
                description: '',
                stateVersion: ExerciseState.currentStateVersion,
                version: 1,
                owner,
                visibility: 'private',
                draftState: false,
            })
            .returning();

        return this.onlySingle(result);
    }

    /**
     * @deprecated
     * TODO: @Quixelation
     */
    public async createCollectionVersion(entityId: Marketplace.Set.EntityId) {
        const latestVersion =
            await this.getLatestCollectionByEntityId(entityId);

        if (!latestVersion) {
            throw new Error('no latest version found');
        }

        const newVersion = latestVersion.version + 1;

        const result = await this.databaseConnection
            .insert(exerciseElementSetTable)
            .values({
                ...latestVersion,
                versionId: undefined, // versionId will be generated by the database
                version: newVersion,
            })
            .returning();

        return this.onlySingle(result);
    }

    public async createElementVersion(data: {
        content: Marketplace.ExerciseElementObjectUnion;
        version: number;
        entityId?: Marketplace.Element.EntityId;
    }) {
        const result = await this.databaseConnection
            .insert(exerciseElementTemplateTable)
            .values({
                version: data.version,
                stateVersion: ExerciseState.currentStateVersion,
                title: data.content.name,
                description: '',
                content: data.content,
                entityId: data.entityId,
                createdBy: 'test-owner', //TODO: @Quixelation
            })
            .returning();

        return this.onlySingle(result);
    }

    public async addElementToCollection(
        elementVersionId: Marketplace.Element.VersionId,
        setVersionId: Marketplace.Set.VersionId
    ) {
        const element = this.onlySingleStrict(
            await this.databaseConnection
                .select()
                .from(exerciseElementTemplateTable)
                .where(
                    eq(exerciseElementTemplateTable.versionId, elementVersionId)
                )
        );

        const set = this.onlySingleStrict(
            await this.databaseConnection
                .select()
                .from(exerciseElementSetTable)
                .where(eq(exerciseElementSetTable.versionId, setVersionId))
        );

        if (set.draftState === false) {
            throw new Error(
                'Can only add exercise objects to sets in draft state'
            );
        }

        await this.databaseConnection
            .delete(elementTemplateToSetMappingTable)
            .where(
                and(
                    eq(
                        elementTemplateToSetMappingTable.setVersionId,
                        setVersionId
                    ),
                    eq(
                        elementTemplateToSetMappingTable.elementEntityId,
                        element.entityId
                    )
                )
            );

        return await this.databaseConnection
            .insert(elementTemplateToSetMappingTable)
            .values({
                setEntityId: set.entityId,
                setVersionId,
                elementEntityId: element.entityId,
                elementVersionId,
            })
            .returning();
    }

    public async copyDependenciesBetweenCollections(
        sourceCollectionVersionId: Marketplace.Set.VersionId,
        targetCollectionVersionId: Marketplace.Set.VersionId
    ) {
        const targetCollection = this.strict(
            await this.getCollectionByVersionId(targetCollectionVersionId)
        );
        const dependencies = await this.getCollectionVersionDependencies(
            sourceCollectionVersionId
        );

        await this.databaseConnection.transaction(async (tx) => {
            for (const dependency of dependencies) {
                await tx.insert(collectionDependencyMappingTable).values({
                    collectionVersionId: dependency.collectionVersionId,
                    collectionEntityId: dependency.collectionEntityId,
                    dependentCollectionVersionId: targetCollection.versionId,
                    dependentCollectionEntityId: targetCollection.entityId,
                });
            }
        });
    }

    public async copyReferencesBetweenCollections(
        sourceSetVersionId: Marketplace.Set.VersionId,
        targetSetVersionId: Marketplace.Set.VersionId
    ) {
        this.databaseConnection.insert(elementTemplateToSetMappingTable).select(
            this.databaseConnection
                .select({
                    // INFO: This is order-sensitive, based on the order in the schema
                    // and requires ALL fields (even defaulted ones) to be selected
                    setEntityId: elementTemplateToSetMappingTable.setEntityId,
                    setVersionId: sql<string>`${targetSetVersionId}`.as(
                        'setVersionId'
                    ),
                    elementEntityId:
                        elementTemplateToSetMappingTable.elementEntityId,
                    elementVersionId:
                        elementTemplateToSetMappingTable.elementVersionId,
                } satisfies Record<
                    keyof typeof elementTemplateToSetMappingTable.$inferInsert,
                    any
                >)
                .from(elementTemplateToSetMappingTable)
                .where(
                    eq(
                        elementTemplateToSetMappingTable.setVersionId,
                        sourceSetVersionId
                    )
                )
        );
    }

    public async copyElementsBetweenCollections(
        source: {
            entityId: Marketplace.Set.EntityId;
            versionId: Marketplace.Set.VersionId;
        },
        target: {
            entityId: Marketplace.Set.EntityId;
            versionId: Marketplace.Set.VersionId;
        }
    ) {
        console.log(
            `Copying elements from set version ${source.versionId} to set version ${target.versionId}`
        );
        await this.databaseConnection.transaction(async (tx) => {
            const targetSet = this.onlySingleStrict(
                await tx
                    .select()
                    .from(exerciseElementSetTable)
                    .where(
                        eq(exerciseElementSetTable.versionId, target.versionId)
                    )
            );

            if (targetSet.draftState === false) {
                throw new Error(
                    'Can only copy exercise objects to sets in draft state'
                );
            }

            const createdElements = await tx
                .insert(exerciseElementTemplateTable)
                .select(
                    tx
                        .select({
                            // INFO: This is order-sensitive, based on the order in the schema
                            // and requires ALL fields (even defaulted ones) to be selected
                            versionId:
                                sql`'element_version_' || uuid_generate_v4()`.as(
                                    'versionId'
                                ),
                            entityId:
                                sql`'element_entity_' || uuid_generate_v4()`.as(
                                    'entityId'
                                ),
                            version: sql<number>`1`.as('version'),
                            stateVersion:
                                latestExerciseElementTemplateView.stateVersion,
                            createdBy: sql<string>`${targetSet.owner}`.as(
                                'createdBy'
                            ),
                            createdAt: sql`now()`.as('createdAt'),
                            title: latestExerciseElementTemplateView.title,
                            description:
                                latestExerciseElementTemplateView.description,
                            content: latestExerciseElementTemplateView.content,
                        } satisfies Record<
                            keyof typeof exerciseElementTemplateTable.$inferInsert,
                            any
                        >)
                        .from(latestExerciseElementTemplateView)
                        .innerJoin(
                            elementTemplateToSetMappingTable,
                            eq(
                                latestExerciseElementTemplateView.versionId,
                                elementTemplateToSetMappingTable.elementVersionId
                            )
                        )
                        .where(
                            eq(
                                elementTemplateToSetMappingTable.setVersionId,
                                source.versionId
                            )
                        )
                )
                .returning();

            await tx.insert(elementTemplateToSetMappingTable).values(
                createdElements.map((element) => ({
                    setEntityId: target.entityId,
                    setVersionId: target.versionId,
                    elementEntityId: element.entityId,
                    elementVersionId: element.versionId,
                }))
            );
        });
    }

    public async getCollectionByVersionId(
        versionId: Marketplace.Set.VersionId
    ) {
        const result = await this.databaseConnection
            .select()
            .from(exerciseElementSetTable)
            .where(eq(exerciseElementSetTable.versionId, versionId));

        return this.onlySingle(result);
    }

    public async getLatestCollectionForUser(userId: string) {
        const latestCollections = this.latestCollections({
            allowDraftState: true,
        });

        const result = this.databaseConnection
            .with(latestCollections)
            .select()
            .from(latestCollections);
        //TODO: @Quixelation
        //.where(eq(exerciseElementSetTable.owner, userId));

        return result;
    }

    public async getElementsOfCollectionVersion(
        setVersionId: Marketplace.Set.VersionId
    ) {
        return await this.databaseConnection
            .select(getTableColumns(exerciseElementTemplateTable))
            .from(exerciseElementTemplateTable)
            .leftJoin(
                elementTemplateToSetMappingTable,
                eq(
                    exerciseElementTemplateTable.versionId,
                    elementTemplateToSetMappingTable.elementVersionId
                )
            )
            .where(
                eq(elementTemplateToSetMappingTable.setVersionId, setVersionId)
            );
    }

    public async getLatestElementVersion(
        entityId: Marketplace.Element.EntityId
    ) {
        const result = await this.databaseConnection
            .select()
            .from(latestExerciseElementTemplateView)
            .where(eq(latestExerciseElementTemplateView.entityId, entityId));

        return this.onlySingle(result);
    }

    public async removeElementFromCollection(
        elementEntityId: Marketplace.Element.EntityId,
        setVersionId: Marketplace.Set.VersionId
    ) {
        await this.databaseConnection
            .delete(elementTemplateToSetMappingTable)
            .where(
                and(
                    eq(
                        elementTemplateToSetMappingTable.elementEntityId,
                        elementEntityId
                    ),
                    eq(
                        elementTemplateToSetMappingTable.setVersionId,
                        setVersionId
                    )
                )
            );
    }

    public async deleteCollection(entityId: Marketplace.Set.EntityId) {
        await this.databaseConnection
            .delete(exerciseElementSetTable)
            .where(eq(exerciseElementSetTable.entityId, entityId));
    }

    public async getElementVersions(entityId: Marketplace.Element.EntityId) {
        const result = await this.databaseConnection
            .select()
            .from(exerciseElementTemplateTable)
            .where(eq(exerciseElementTemplateTable.entityId, entityId))
            .orderBy(desc(exerciseElementTemplateTable.version));

        return result;
    }

    public async setCollectionVisibility(
        setEntityId: Marketplace.Set.EntityId,
        visibility: Marketplace.ElementSetVisibility
    ) {
        console.log(
            `Updating visibility for setEntityId ${setEntityId} to ${visibility}`
        );
        return this.onlySingleStrict(
            await this.databaseConnection
                .update(exerciseElementSetTable)
                .set({
                    visibility,
                })
                .where(eq(exerciseElementSetTable.entityId, setEntityId))
                .returning()
        );
    }

    public async getLatestCollectionByEntityId(
        setEntityId: Marketplace.Set.EntityId,
        opts?: { allowDraftState?: boolean }
    ) {
        console.log(opts);
        const latestCollections = this.latestCollections({
            allowDraftState: opts?.allowDraftState ?? true,
        });

        return this.onlySingle(
            await this.databaseConnection
                .with(latestCollections)
                .select()
                .from(latestCollections)
                .where(eq(latestCollections.entityId, setEntityId))
        );
    }

    public async getLatestCollectionOfElementEntity(
        elementEntityId: Marketplace.Element.EntityId
    ) {
        return this.onlySingle(
            await this.databaseConnection
                .select(getTableColumns(exerciseElementSetTable))
                .from(exerciseElementSetTable)
                .innerJoin(
                    elementTemplateToSetMappingTable,
                    eq(
                        exerciseElementSetTable.versionId,
                        elementTemplateToSetMappingTable.setVersionId
                    )
                )
                .where(
                    eq(
                        elementTemplateToSetMappingTable.elementEntityId,
                        elementEntityId
                    )
                )
                .orderBy(desc(exerciseElementSetTable.version))
                .limit(1)
        );
    }
}
